{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7d57d94f",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "available_pizzas = ['margarita', 'pollo', '4cheese', 'bolognese', 'vegetarian']\n",
    "available_toppings = ['mushroom', 'onions', 'green pepper', 'extra cheese']\n",
    "pizza_prices = {'margarita': 5, 'pollo': 7, '4cheese': 6, 'bolognese': 8, 'vegetarian': 6.5}\n",
    "topping_prices = {'mushroom':1, 'onions': 2, 'green pepper':3, 'extra cheese':4}\n",
    "sub_total = []\n",
    "final_order = {}\n",
    "customer_adress = {}\n",
    "\n",
    "\n",
    "\n",
    "print(\"Hi, welcome to our text based pizza ordering\")\n",
    "order_pizza = True\n",
    "while order_pizza:    \n",
    "    print(\"Please choose a pizza: \")\n",
    "    print()\n",
    "    for pizzas in available_pizzas:\n",
    "        print(pizzas)\n",
    "        print()\n",
    "    while True:\n",
    "        pizza = input(\"which pizza would you like to order?\")\n",
    "        if pizza in available_pizzas:\n",
    "            print(f\"You have ordered a {pizza}.\")\n",
    "            sub_total.append(pizza_prices[pizza])\n",
    "            break\n",
    "        if pizza not in available_pizzas:\n",
    "            print(f\"I am sorry, we currently do not have {pizza}.\")\n",
    "\n",
    "\n",
    "    order_topping = True\n",
    "    print(\"This is the list of available extra toppings: \")\n",
    "    for toppings in available_toppings:\n",
    "        print(toppings)\n",
    "        print()\n",
    "    while order_topping:\n",
    "        extra_topping = input(\"Would you like an extra topping? yes or no?\")\n",
    "        if extra_topping == \"yes\":\n",
    "            topping = input(\"Which one would you like to add?\")\n",
    "            if topping in available_toppings:\n",
    "                final_order.setdefault(pizza, [])\n",
    "                final_order[pizza].append(topping)\n",
    "                print(f\"I have added {topping}.\")\n",
    "                sub_total.append(topping_prices[topping])\n",
    "            else:\n",
    "                print(f\"I am sorry, we don't have {topping} available.\")\n",
    "\n",
    "        elif extra_topping == \"no\":\n",
    "            break\n",
    "    extra_pizza = input(\"Would you like to order another pizza?\")\n",
    "    if extra_pizza == \"no\":\n",
    "        for key, value in final_order.items():\n",
    "            print(f\"\\nYou have order a {key} pizza with {value}\")\n",
    "        check_order = True\n",
    "        while check_order:\n",
    "            print()\n",
    "            order_correct = input(\"Is this correct? yes/no \")\n",
    "            if order_correct == \"yes\":\n",
    "                check_order = False\n",
    "                order_pizza = False\n",
    "            if order_correct == \"no\":\n",
    "                print(final_order)\n",
    "                add_remove = input(\"would you like to add or remove? \")\n",
    "                if add_remove == \"remove\":\n",
    "                    remove = input(\"Which pizza would you like to remove? \")\n",
    "                    del final_order[remove]\n",
    "                    print(final_order)\n",
    "                if add_remove == \"add\":\n",
    "                    check_order = False\n",
    "\n",
    "\n",
    "print(f\"\\nYour total order price is: ${sum(sub_total)}\")\n",
    "\n",
    "print(\"Please provide us with your name, adress and phonenumber\")\n",
    "customer_adress['name'] = input(\"what is your name?\")\n",
    "customer_adress['street_name'] = input(\"What is your streetname and housenumber?\")\n",
    "customer_adress['postalcode'] = input(\"What is the postalcode and cityname?\")\n",
    "customer_adress['phonenumber'] = input(\"What is your phonenumber?\")\n",
    "print()\n",
    "print(f\"Thank you for your order {customer_adress['name']}.\")\n",
    "print()\n",
    "print(\"We will deliver your order to this adres ASAP\")\n",
    "print()\n",
    "print(customer_adress['street_name'])\n",
    "print(customer_adress['postalcode'])\n",
    "print()\n",
    "print(f\"we will contact you on {customer_adress['phonenumber']} if anything comes up.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
